
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author PC
 */
public class ThePaintBrush extends JFrame {

    private DrawingPanel drawingPanel;

    public ThePaintBrush() {

        this.setTitle("Paint Brush");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(800, 600);

        initComponents();
        drawingPanel = new DrawingPanel();
        theDrawingPanel.setLayout(new BorderLayout());
        theDrawingPanel.add(drawingPanel, BorderLayout.CENTER);

        clearBtn.addActionListener(e -> drawingPanel.clear());
        lineBtn.addActionListener(e -> drawingPanel.setTool("Line"));
        rectangleBtn.addActionListener(e -> drawingPanel.setTool("Rectangle"));
        ovalBtn.addActionListener(e -> drawingPanel.setTool("Oval"));
        freehandBtn.addActionListener(e -> drawingPanel.setTool("Freehand"));
        triangleBtn.addActionListener(e -> drawingPanel.setTool("Triangle"));
        eraserBtn.addActionListener(e -> drawingPanel.setTool("Eraser"));
        fillChBx.addActionListener(e -> drawingPanel.setFill(fillChBx.isSelected()));
        colorButton.addActionListener(e -> {
            Color selectedColor = JColorChooser.showDialog(this, "Choose a color", drawingPanel.getCurrentColor());
            if (selectedColor != null) {
                drawingPanel.setColor(selectedColor);
            }
        });
        getContentPane().add(colorButton, BorderLayout.SOUTH);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new ThePaintBrush().setVisible(true));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lineBtn = new javax.swing.JButton();
        rectangleBtn = new javax.swing.JButton();
        ovalBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        theDrawingPanel = new javax.swing.JPanel();
        colorButton = new javax.swing.JButton();
        freehandBtn = new javax.swing.JButton();
        fillChBx = new javax.swing.JCheckBox();
        triangleBtn = new javax.swing.JButton();
        eraserBtn = new javax.swing.JButton();

        setTitle("Paint Brush");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(51, 204, 0));

        jLabel1.setText("Functions:");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Paint Mode:");

        lineBtn.setText("Line");

        rectangleBtn.setText("Rectangle");

        ovalBtn.setText("Oval");

        jLabel3.setText("Colors");

        theDrawingPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout theDrawingPanelLayout = new javax.swing.GroupLayout(theDrawingPanel);
        theDrawingPanel.setLayout(theDrawingPanelLayout);
        theDrawingPanelLayout.setHorizontalGroup(
            theDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        theDrawingPanelLayout.setVerticalGroup(
            theDrawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        colorButton.setText("Choose Color");
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        freehandBtn.setText("Freehand");
        freehandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freehandBtnActionPerformed(evt);
            }
        });

        fillChBx.setText("Fill");

        triangleBtn.setText("Triangle");

        eraserBtn.setText("Eraser");
        eraserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraserBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(theDrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eraserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lineBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rectangleBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triangleBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ovalBtn)
                        .addGap(18, 18, 18)
                        .addComponent(freehandBtn)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorButton))
                    .addComponent(fillChBx))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clearBtn)
                    .addComponent(jLabel2)
                    .addComponent(lineBtn)
                    .addComponent(rectangleBtn)
                    .addComponent(jLabel3)
                    .addComponent(colorButton)
                    .addComponent(triangleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fillChBx)
                        .addComponent(ovalBtn)
                        .addComponent(freehandBtn))
                    .addComponent(eraserBtn))
                .addGap(21, 21, 21)
                .addComponent(theDrawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtnActionPerformed

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorButtonActionPerformed

    private void freehandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freehandBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freehandBtnActionPerformed

    private void eraserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraserBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eraserBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton colorButton;
    private javax.swing.JButton eraserBtn;
    private javax.swing.JCheckBox fillChBx;
    private javax.swing.JButton freehandBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lineBtn;
    private javax.swing.JButton ovalBtn;
    private javax.swing.JButton rectangleBtn;
    private javax.swing.JPanel theDrawingPanel;
    private javax.swing.JButton triangleBtn;
    // End of variables declaration//GEN-END:variables
}
